AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"

Rails:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "bin/setup"
    - "bin/update"

Style/StringLiterals:
  EnforcedStyle: double_quotes
