# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6233a0e83db38d632b98cd67190fb7deaeb085fa02de3ba94aeb6a901f3e09b3e5e12e0fdc880c9e2ac463b302a258b04052acf6cf20a5c736af32a3f62834b5

test:
  secret_key_base: 1093ee36bbc06b4ff1ecebf12635c166be177fbab5f7c7ecf8b0cf70a83662eaa7bc35bba5a081541145e57efa89971446a24962fbc9bb574e18d439d6ca1aa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
